In [1]:
import pandas as pd
import os
import csv
import stratilib as sl

{'S': 'Sharp', 'E': 'Erosion', 'G': 'Gradational'}

In [2]:
cwd = os.getcwd()

In [3]:
datos = pd.read_excel(cwd + "\datos.xlsx")
datos

,Formación,Espesor,Litología,Contacto,Granulometría,Estructuras / Fósiles,Litología 2,Descripción,Notas
0,NaN,30,Sr,E,m,r,NaN,Arenisca fina con intraclastos,NaN
1,NaN,25,Sr,G,f,r,NaN,Arenisca media,NaN
2,NaN,100,Gp,NaN,g,r,NaN,Grava,NaN
3,NaN,40,St,E,vf,NaN,NaN,NaN,NaN

### Definiciones de diccionarios para cargar en CSV de SedLog (sedlogdef.py)

In [16]:
#Variables para 'BASE BOUNDARY'
DICT_SL_CONTACTS = {'S':'Sharp',
                    'E':'Erosion',
                    'G':'Gradational'}

#Variables para SYMBOLS IN BED' y 'SYMBOLS/STRUCTURES'
DICT_SL_STRUCTURES = {'r':'Current ripple cross-lamination',
                   't':'Trough cross bedding',
                   'p':'Planar cross bedding',
                   'x1':'Fine ash',
                   'x1':'Coarse ash'}

#Variables para 'GRAIN SIZE BASE' y 'GRAIN SIZE TOP'
DICT_SL_GRAINS = {'cl':'clay',
                  'cls':'clay//silt',
                  's':'silt',
                  'svf':'silt//vf',
                  'vf':'vf',
                  'vff':'vf//f',
                  'f':'f',
                  'fm':'f//m',
                  'm':'m',
                  'mv':'m//c',
                  'c':'c',
                  'cvc':'c//vc',
                  'vc':'vc',
                  'vcg':'vc//granule',
                  'g':'granule',
                  'gp':'granule//pebble',
                  'p':'pebble',
                  'pco':'pebble//cobble',
                  'co':'cobble',
                  'cob':'cobble//boulder',
                  'b':'boulder'}


#Según tipos presentes en SEDLOG

DICT_SL_LITHO = {'M':'Mudstone',
              'x1':'Claystone',
              'x1':'Shale',
              'x1':'Siltstone',
              'S':'Sandstone',
              'G':'Conglomerate',
              'x1':'Coal',
              'x1':'Limestone',
              'x1':'Chert',             
              'x1':'Volcaniclastic',
              
              'x1':'Lime mudstone',
              'x1':'Wackestone',
              'x1':'Packestone',
              'x1':'Grainstone',
              'x1':'Halite',
              'Gy':'Gypsum/Anhydrite',
              'D':'Dolomite',
              
              'B':'Breccia',
              'x1':'Matrix-supported conglomerate',
              'x1':'Clast-supported conglomerate',
              'x1':'Lava',
              'x1':'Fine ash',
              'x1':'Coarse ash'}

In [17]:
datos

,Pozo,Fm,Contacto,Tope,Base,Espesor,Litología,Granulometría,Estructuras,Fósiles,Descripción,Gran
0,NaN,NaN,NaN,0,3.0,3.0,C,NaN,NaN,NaN,,1.0
1,NaN,NaN,NaN,3,15.0,12.0,M,NaN,NaN,NaN,,1.0
2,NaN,NaN,NaN,15,18.0,3.0,M,NaN,NaN,NaN,alto angulo,1.0
3,NaN,NaN,NaN,18,21.0,3.0,B,NaN,NaN,NaN,,1.0
4,NaN,NaN,NaN,21,36.0,15.0,B,NaN,NaN,NaN,,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
182,NaN,NaN,NaN,2030,2032.0,2.0,D,NaN,NaN,NaN,,1.0
183,NaN,NaN,NaN,2032,2094.0,62.0,D,NaN,NaN,NaN,,1.0
184,NaN,NaN,NaN,2094,2128.0,34.0,D,NaN,NaN,NaN,,1.0
185,NaN,NaN,NaN,2128,2130.0,2.0,D,NaN,NaN,NaN,,1.0
186,NaN,NaN,NaN,2130,2229.0,99.0,D,NaN,NaN,NaN,,1.0

### Funciones en sedlogfunc.py

In [23]:
datos = sl.read_lito("Litotope.xlsx")
to_sedlog_csv(datos)

,THICKNESS (CM),BASE BOUNDARY,LITHOLOGY,LITHOLOGY %,LITHOLOGY2,LITHOLOGY2 %,LITHOLOGY3,LITHOLOGY3 %,GRAIN SIZE BASE,PHI VALUES BASE,...,BIOTURBATION TYPE,INTENSITY,PALAEOCURRENT VALUES,FACIES,OTHER1 TEXT,OTHER1 SYMBOL,OTHER2 TEXT,OTHER2 SYMBOL,OTHER3 TEXT,OTHER3 SYMBOL
0,3.0,<none>,None,100,<none>,0,<none>,0,<none>,0.0,...,<none>,0,"""""",0,"""""","""""","""""","""""","""""",""""""
1,12.0,<none>,Mudstone,100,<none>,0,<none>,0,<none>,0.0,...,<none>,0,"""""",0,"""""","""""","""""","""""","""""",""""""
2,3.0,<none>,Mudstone,100,<none>,0,<none>,0,<none>,0.0,...,<none>,0,"""""",0,"""""","""""","""""","""""","""""",""""""
3,3.0,<none>,Breccia,100,<none>,0,<none>,0,<none>,0.0,...,<none>,0,"""""",0,"""""","""""","""""","""""","""""",""""""
4,15.0,<none>,Breccia,100,<none>,0,<none>,0,<none>,0.0,...,<none>,0,"""""",0,"""""","""""","""""","""""","""""",""""""
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,2.0,<none>,Dolomite,100,<none>,0,<none>,0,<none>,0.0,...,<none>,0,"""""",0,"""""","""""","""""","""""","""""",""""""
183,62.0,<none>,Dolomite,100,<none>,0,<none>,0,<none>,0.0,...,<none>,0,"""""",0,"""""","""""","""""","""""","""""",""""""
184,34.0,<none>,Dolomite,100,<none>,0,<none>,0,<none>,0.0,...,<none>,0,"""""",0,"""""","""""","""""","""""","""""",""""""
185,2.0,<none>,Dolomite,100,<none>,0,<none>,0,<none>,0.0,...,<none>,0,"""""",0,"""""","""""","""""","""""","""""",""""""
186,99.0,<none>,Dolomite,100,<none>,0,<none>,0,<none>,0.0,...,<none>,0,"""""",0,"""""","""""","""""","""""","""""",""""""

In [24]:
def to_sedlog_csv(datos):
    #Columnas del SedLog para cargar por CSV
    sedLogCSV = pd.DataFrame()
    vacio ='""'

    for i in range(len(datos)):
        sedLogCSV = sedLogCSV.append(
            {'THICKNESS (CM)': datos['Espesor'][i], 
             'BASE BOUNDARY': DICT_SL_CONTACTS.get(datos['Contacto'][i]) if datos['Contacto'][i] in DICT_SL_CONTACTS else '<none>', 
             'LITHOLOGY': DICT_SL_LITHO.get(datos['Litología'][i]), 
             'LITHOLOGY %': '100',
             'LITHOLOGY2': '<none>', #if pd.isna(datos['Litología 2'][i]) else getLitho(datos['Litología 2'][i]),
             'LITHOLOGY2 %': '0', 
             'LITHOLOGY3': '<none>', 
             'LITHOLOGY3 %': '0',
             'GRAIN SIZE BASE': DICT_SL_GRAINS.get(datos['Granulometría'][i]) if datos['Granulometría'][i] in DICT_SL_GRAINS else '<none>',
             'PHI VALUES BASE': 0, 
             'GRAIN SIZE TOP': DICT_SL_GRAINS.get(datos['Granulometría'][i]) if datos['Granulometría'][i] in DICT_SL_GRAINS else '<none>',
             'PHI VALUES TOP': 0, 
             'SYMBOLS IN BED': DICT_SL_STRUCTURES.get(datos['Estructuras'][i]) if datos['Estructuras'][i] in DICT_SL_STRUCTURES else '<none>', 
             'SYMBOLS/STRUCTURES': vacio,       
             'NOTES COLUMN': vacio,             
             'BIOTURBATION TYPE': '<none>', 
             'INTENSITY': '0',
             'PALAEOCURRENT VALUES': vacio, 
             'FACIES': '0', 
             'OTHER1 TEXT': vacio, 
             'OTHER1 SYMBOL': vacio,
             'OTHER2 TEXT': vacio, 
             'OTHER2 SYMBOL': vacio,                      
             'OTHER3 TEXT': vacio, 
             'OTHER3 SYMBOL':vacio}

            ,ignore_index =True)

    sedLogCSV.to_csv("sedLogCSV.csv", index =False,quoting=csv.QUOTE_NONE)
    return sedLogCSV

In [8]:
#df = pd.read_csv(cwd + "\\pru.csv")
#df

In [ ]:
#sedLogCSV.to_csv(cwd + "\\sedLogCSV.csv", index =False)